### ISSUE TITLE
Segfault on old policies

### ISSUE THREAD

**Issue by bsloane1650** [SELinuxProject/selinux#239]
libsepol has special handling to issue a warning when old policies have duplicate filename transition rules. I am running into an issue where p->sym_val_to_name is all NULL when this handler gets called, triggering a segfault. Rebuilding libsepol without the relevent warning appears to resolve the issue.

Stack trace from running apol.

```
#0  0x00007ffff7b633bd in filename_trans_read (p=0x5555560d9190, fp=0x555556243980) at policydb.c:2660
SELinuxProject/setools#1  0x00007ffff7b65667 in policydb_read (p=0x5555560d9190, fp=0x555556243980, verbose=verbose@entry=0) at policydb.c:4050
SELinuxProject/setools#2  0x00007ffff7b66737 in sepol_policydb_read (p=<optimized out>, pf=<optimized out>) at policydb_public.c:177
SELinuxProject/setools#3  0x00007fffe9ccc959 in __pyx_f_7setools_9policyrep_13SELinuxPolicy__load_policy (__pyx_v_self=0x7fffe403fd68, __pyx_v_filename=0x7ffff6146150)
    at setools/policyrep.c:82464
SELinuxProject/setools#4  0x00007fffe9cae55b in __pyx_pf_7setools_9policyrep_13SELinuxPolicy___cinit__ (__pyx_v_policyfile=<optimized out>, __pyx_v_self=0x7fffe403fd68)
    at setools/policyrep.c:70264
SELinuxProject/setools#5  __pyx_pw_7setools_9policyrep_13SELinuxPolicy_1__cinit__ (__pyx_kwds=<optimized out>, __pyx_args=<optimized out>, __pyx_v_self=0x7fffe403fd68)
    at setools/policyrep.c:4621
SELinuxProject/setools#6  __pyx_tp_new_7setools_9policyrep_SELinuxPolicy (t=<optimized out>, a=<optimized out>, k=<optimized out>) at setools/policyrep.c:15294
SELinuxProject/setools#7  0x00007ffff7514975 in type_call () from /lib64/libpython3.6m.so.1.0
SELinuxProject/setools#8  0x00007ffff74a635b in _PyObject_FastCallDict () from /lib64/libpython3.6m.so.1.0
SELinuxProject/setools#9  0x00007ffff7522ab1 in call_function () from /lib64/libpython3.6m.so.1.0
SELinuxProject/setools#10 0x00007ffff7552a6a in _PyEval_EvalFrameDefault () from /lib64/libpython3.6m.so.1.0
SELinuxProject/setools#11 0x00007ffff74de42a in fast_function () from /lib64/libpython3.6m.so.1.0
SELinuxProject/setools#12 0x00007ffff7522a32 in call_function () from /lib64/libpython3.6m.so.1.0
SELinuxProject/setools#13 0x00007ffff7552a6a in _PyEval_EvalFrameDefault () from /lib64/libpython3.6m.so.1.0
SELinuxProject/setools#14 0x00007ffff74a4be8 in _PyEval_EvalCodeWithName () from /lib64/libpython3.6m.so.1.0
SELinuxProject/setools#15 0x00007ffff74a5dfe in _PyFunction_FastCallDict () from /lib64/libpython3.6m.so.1.0
SELinuxProject/setools#16 0x00007ffff74a65ee in _PyObject_FastCallDict () from /lib64/libpython3.6m.so.1.0
SELinuxProject/setools#17 0x00007ffff74b1a80 in _PyObject_Call_Prepend () from /lib64/libpython3.6m.so.1.0
SELinuxProject/setools#18 0x00007ffff74a6993 in PyObject_Call () from /lib64/libpython3.6m.so.1.0
SELinuxProject/setools#19 0x00007ffff7518466 in slot_tp_init () from /lib64/libpython3.6m.so.1.0
SELinuxProject/setools#20 0x00007ffff75149c2 in type_call () from /lib64/libpython3.6m.so.1.0
SELinuxProject/setools#21 0x00007ffff74a635b in _PyObject_FastCallDict () from /lib64/libpython3.6m.so.1.0
SELinuxProject/setools#22 0x00007ffff7522ab1 in call_function () from /lib64/libpython3.6m.so.1.0
SELinuxProject/setools#23 0x00007ffff7552a6a in _PyEval_EvalFrameDefault () from /lib64/libpython3.6m.so.1.0
SELinuxProject/setools#24 0x00007ffff752cda7 in PyEval_EvalCodeEx () from /lib64/libpython3.6m.so.1.0
SELinuxProject/setools#25 0x00007ffff752dc6b in PyEval_EvalCode () from /lib64/libpython3.6m.so.1.0
SELinuxProject/setools#26 0x00007ffff7569356 in builtin_exec () from /lib64/libpython3.6m.so.1.0
SELinuxProject/setools#27 0x00007ffff75144c2 in _PyCFunction_FastCallDict () from /lib64/libpython3.6m.so.1.0
SELinuxProject/setools#28 0x00007ffff752294d in call_function () from /lib64/libpython3.6m.so.1.0
SELinuxProject/setools#29 0x00007ffff7552a6a in _PyEval_EvalFrameDefault () from /lib64/libpython3.6m.so.1.0
SELinuxProject/setools#30 0x00007ffff74de42a in fast_function () from /lib64/libpython3.6m.so.1.0
SELinuxProject/setools#31 0x00007ffff7522a32 in call_function () from /lib64/libpython3.6m.so.1.0
SELinuxProject/setools#32 0x00007ffff7552a6a in _PyEval_EvalFrameDefault () from /lib64/libpython3.6m.so.1.0
SELinuxProject/setools#33 0x00007ffff74de42a in fast_function () from /lib64/libpython3.6m.so.1.0
SELinuxProject/setools#34 0x00007ffff7522a32 in call_function () from /lib64/libpython3.6m.so.1.0
SELinuxProject/setools#35 0x00007ffff7552a6a in _PyEval_EvalFrameDefault () from /lib64/libpython3.6m.so.1.0
SELinuxProject/setools#36 0x00007ffff752cda7 in PyEval_EvalCodeEx () from /lib64/libpython3.6m.so.1.0
SELinuxProject/setools#37 0x00007ffff752dc6b in PyEval_EvalCode () from /lib64/libpython3.6m.so.1.0
SELinuxProject/setools#38 0x00007ffff75bf552 in run_mod () from /lib64/libpython3.6m.so.1.0
SELinuxProject/setools#39 0x00007ffff75c07a7 in PyRun_FileExFlags () from /lib64/libpython3.6m.so.1.0
SELinuxProject/setools#40 0x00007ffff75c22af in PyRun_SimpleFileExFlags () from /lib64/libpython3.6m.so.1.0
SELinuxProject/setools#41 0x00007ffff75c33ab in Py_Main () from /lib64/libpython3.6m.so.1.0
--Type <RET> for more, q to quit, c to continue without paging--
SELinuxProject/setools#42 0x0000555555554c68 in main ()

```

```
(gdb) print  p->sym_val_to_name
$8 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}
```

Code in libsepol I removed to avoid the issue
```
                        /*
                         * Some old policies were wrongly generated with
                         * duplicate filename transition rules.  For backward
                         * compatibility, do not reject such policies, just
                         * issue a warning and ignore the duplicate.
                         */
                        WARN(fp->handle,
                             "Duplicate name-based type_transition %s %s:%s \"%s\":  %s, ignoring",
                             p->p_type_val_to_name[ft->stype - 1],
                             p->p_type_val_to_name[ft->ttype - 1],
                             p->p_class_val_to_name[ft->tclass - 1],
                             ft->name,
                             p->p_type_val_to_name[otype->otype - 1]);
```

I'm not sure if this is an issue with setools or libsepol.

Tested with:
* setools 4.3.0
* libsepol 6950ee07d0cfaf93f0c41cb27cfdc3e9e6c17e81 (master as of may 11)

**Comment by stephensmalley** [comment]
Moved to the selinux userspace project since it is a libsepol bug.  Can you provide a copy of the policy that produced the fault?

**Comment by stephensmalley** [comment]
Proposed fix here: https://github.com/stephensmalley/selinux/commit/4f1a737297c7a139b0c2a312d4051eed5bfa92eb

**Comment by bsloane1650** [comment]
> Moved to the selinux userspace project since it is a libsepol bug. Can you provide a copy of the policy that produced the fault?

Unfortunately, I am not at liberty to share the policy that produces this.

**Comment by stephensmalley** [comment]
Ok, can you test that the fix cited above works for you?

**Comment by bsloane1650** [comment]
The above cited fix works for me.
