### ISSUE TITLE
A few tests seem to be failing under UBsan

### ISSUE THREAD

**Issue by evverx** [SELinuxProject/selinux#253]
I built the project with UBsan and then ran the unit tests. Some of them failed with
```
Suite: cond
  Test: cond_expr_equal ...passedlink.c:193:3: runtime error: null pointer passed as argument 2, which is declared to never be null
    #0 0x4cb47b in permission_copy_callback /home/vagrant/selinux/libsepol/src/link.c:193
    #1 0x4bcad6 in hashtab_map /home/vagrant/selinux/libsepol/src/hashtab.c:234
    #2 0x4cec57 in class_copy_callback /home/vagrant/selinux/libsepol/src/link.c:333
    #3 0x4bcad6 in hashtab_map /home/vagrant/selinux/libsepol/src/hashtab.c:234
    #4 0x4e92a9 in copy_identifiers /home/vagrant/selinux/libsepol/src/link.c:1617
    #5 0x4fd7f2 in link_modules /home/vagrant/selinux/libsepol/src/link.c:2594
    #6 0x4139bf in linker_test_init /home/vagrant/selinux/libsepol/tests/test-linker.c:82
    #7 0x7f9b814a20ed  (/lib64/libcunit.so.1+0x50ed)
    #8 0x7f9b814a2656 in CU_run_all_tests (/lib64/libcunit.so.1+0x5656)
    #9 0x4036bd in do_tests /home/vagrant/selinux/libsepol/tests/libsepol-tests.c:77
    #10 0x403af3 in main /home/vagrant/selinux/libsepol/tests/libsepol-tests.c:112
    #11 0x7f9b809931a2 in __libc_start_main (/lib64/libc.so.6+0x271a2)
    #12 0x40266d in _start (/home/vagrant/selinux/libsepol/tests/libsepol-tests+0x40266d)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior link.c:193:3 in
```

```
Suite: user
  Test: user_compare ...database_join.c:82:2: runtime error: null pointer passed as argument 1, which is declared to never be null
    #0 0x4f0b53 in dbase_join_cache /home/vagrant/selinux/libsemanage/src/database_join.c:82
    #1 0x43612b in enter_ro /home/vagrant/selinux/libsemanage/src/database.c:39
    #2 0x437872 in dbase_list /home/vagrant/selinux/libsemanage/src/database.c:192
    #3 0x47fa19 in semanage_user_list /home/vagrant/selinux/libsemanage/src/users_policy.c:53
    #4 0x42d462 in get_user_nth /home/vagrant/selinux/libsemanage/tests/test_user.c:122
    #5 0x42dc0c in test_user_compare /home/vagrant/selinux/libsemanage/tests/test_user.c:191
    #6 0x7fa973867faa  (/lib64/libcunit.so.1+0x4faa)
    #7 0x7fa973868248  (/lib64/libcunit.so.1+0x5248)
    #8 0x7fa973868656 in CU_run_all_tests (/lib64/libcunit.so.1+0x5656)
    #9 0x408b7b in do_tests /home/vagrant/selinux/libsemanage/tests/libsemanage-tests.c:89
    #10 0x408fa7 in main /home/vagrant/selinux/libsemanage/tests/libsemanage-tests.c:125
    #11 0x7fa971baf1a2 in __libc_start_main (/lib64/libc.so.6+0x271a2)
    #12 0x40866d in _start (/home/vagrant/selinux/libsemanage/tests/libsemanage-tests+0x40866d)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior database_join.c:82:2 in
```
```
Test: user_modify_del_query_local ...database_join.c:80:2: runtime error: null pointer passed as argument 1, which is declared to never be null
    #0 0x4f0a37 in dbase_join_cache /home/vagrant/selinux/libsemanage/src/database_join.c:80
    #1 0x436abc in enter_rw /home/vagrant/selinux/libsemanage/src/database.c:72
    #2 0x436dbe in dbase_modify /home/vagrant/selinux/libsemanage/src/database.c:87
    #3 0x47edb6 in semanage_user_modify_local /home/vagrant/selinux/libsemanage/src/users_local.c:24
    #4 0x430e52 in test_user_modify_del_query_local /home/vagrant/selinux/libsemanage/tests/test_user.c:568
    #5 0x7fa973867faa  (/lib64/libcunit.so.1+0x4faa)
    #6 0x7fa973868248  (/lib64/libcunit.so.1+0x5248)
    #7 0x7fa973868656 in CU_run_all_tests (/lib64/libcunit.so.1+0x5656)
    #8 0x408b7b in do_tests /home/vagrant/selinux/libsemanage/tests/libsemanage-tests.c:89
    #9 0x408fa7 in main /home/vagrant/selinux/libsemanage/tests/libsemanage-tests.c:125
    #10 0x7fa971baf1a2 in __libc_start_main (/lib64/libc.so.6+0x271a2)
    #11 0x40866d in _start (/home/vagrant/selinux/libsemanage/tests/libsemanage-tests+0x40866d)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior database_join.c:80:2 in
passed
```
I'd also add that It would be great if the tests were run with ASan+UBsan regularly on Travis CI.

By the way, ASan found 571 memory leaks. I'll try to open an issue once I figure out how to extract the useful bits from the log.

**Comment by evverx** [comment]
It was fixed as far as I can remember.
