### ISSUE TITLE
selinux_check_access is not thread-safe

### ISSUE THREAD

**Issue by sethmoo** [SELinuxProject/selinux#287]
By default, `selinux_check_access` does not appear to be thread-safe. It calls `avc_open`, which then calls `avc_init`, passing `NULL` for all callback function tables. The result is that no locking is done for the AVC, which can corrupt the cache it if multiple threads are calling `selinux_check_access`.

It looks like calling `avc_init`, supplying lock callbacks, is the "easy" answer. However, the [`avc_init`](https://github.com/SELinuxProject/selinux/blob/d155b410d4bbc90d28f361b966f0429598da8188/libselinux/man/man3/avc_init.3#L24) man page says that `avc_init` is deprecated. There's a new function for setting callbacks, `selinux_set_callback`, but it does not seem to support locking.

I see a few possible solutions:
1. Update `selinux_set_callback` to support functions for locking. Internally, these functions can set the various `avc_func_*_lock` function pointers.
2. Update the man pages to indicate selinux is simply not intended to be thread-safe anymore.
3. Update the `avc_init` man page, indicating it's safe to use (perhaps un-deprecate, given there's no other way to get thread-safety)
4. There's some code path I've missed, and thread safety is hiding in there somewhere :)

I'm happy to submit patches either way, I just don't know what is preferred by the maintainers.

**Comment by cgzones** [comment]
The call to `avc_open` in `avc_init_once` is guarded by [`__selinux_once`](https://github.com/SELinuxProject/selinux/blob/61fbdce666f24c4a118b249ece6b014d54b65074/libselinux/src/checkAccess.c#L29), which *should* be thread-safe:
https://github.com/SELinuxProject/selinux/blob/61fbdce666f24c4a118b249ece6b014d54b65074/libselinux/src/selinux_internal.h#L15-L23

**Comment by sethmoo** [comment]
The `avc_init_once` call seems fine, for sure. However, it's not initializing any of the locking callbacks in the AVC code. Walking down the call stack we see...
https://github.com/SELinuxProject/selinux/blob/26a4c19ecff545324aa21eb0afbc3d10d3356313/libselinux/src/checkAccess.c#L13-L18

... that `avc_init_once` in turn calls `avc_open`, who internally passes `NULL` to all the function tables:
https://github.com/SELinuxProject/selinux/blob/d155b410d4bbc90d28f361b966f0429598da8188/libselinux/src/avc.c#L241

The fourth parameter is the `lock_cb` function table:
https://github.com/SELinuxProject/selinux/blob/d155b410d4bbc90d28f361b966f0429598da8188/libselinux/src/avc.c#L147-L151

At this point, AVC is configured to not bother do any locking, which means concurrent calls to `selinux_check_access` are going to eventually trounce the cache. For instance, down in `avc_has_perm_no_audit`, it _seems_ like the correct locking is happening:
https://github.com/SELinuxProject/selinux/blob/d155b410d4bbc90d28f361b966f0429598da8188/libselinux/src/avc.c#L770

Unfortunate, `avc_get_lock` is a noop, so we're living dangerously (_very_ dangerously) with multiple threads. Interestingly, with concurrent calls to `selinux_check_access`, things tend to be "just fine" until the cache is exhausted. Once we end up with more than `AVC_CACHE_MAXNODES` entries in the cache, bad things start to happen.

**Comment by sethmoo** [comment]
Oops, apparently I'm not so hot at reading docs. I just noticed "Please submit all bug reports and patches to selinux@vger.kernel.org." as literally the first line of the README.

I can close this bug and email instead, if that's preferred.

**Comment by cgzones** [comment]
Your analysis seems correct and a simple use `selinux_access_check` in multiple threads showed some issues with thread sanitizers.
It's probably best to continue any discussion, proposals and patches (at least man:selinux_check_access(3) should mention whether it's thread-safe) on the mailing list.

p.s.: are you aware of applications using `selinux_access_check` in different threads?

**Comment by sethmoo** [comment]
Thanks, I'll follow-up on the mailing list.

In Android, we are doing `selinux_access_check` from multiple threads. As a work-around, [we slapped a lock around _all_ selinux calls](https://android.googlesource.com/platform/system/security/+/ff188d3a6ca38919e568f0c89f74d90c011526e9) just in case there were other lurking threading issues.

**Comment by ciphergoth** [comment]
[Mailing list followup](https://lore.kernel.org/selinux/CAJsHiNyV2K2g90YsiiY5HZkONHuprTHGq+65Bs-TiCf988NBGA@mail.gmail.com/T/#u)

**Comment by rmsh1216** [comment]
Has this problem been fixed? I seem to be having a similar problem and crashing.
```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x0000ffffb8b1587c in __GI_abort () at abort.c:79
#2  0x0000ffffb8b0d95c in __assert_fail_base (fmt=0xffffb8c0a3a0 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
    assertion=assertion@entry=0xffffb8e38328 "avc_running", file=file@entry=0xffffb8e38320 "avc.c", line=line@entry=74,
    function=function@entry=0xffffb8e381f8 <__PRETTY_FUNCTION__.6554> "avc_context_to_sid_raw") at assert.c:92
#3  0x0000ffffb8b0d9dc in __GI___assert_fail (assertion=assertion@entry=0xffffb8e38328 "avc_running", file=file@entry=0xffffb8e38320 "avc.c", line=line@entry=74,
    function=function@entry=0xffffb8e381f8 <__PRETTY_FUNCTION__.6554> "avc_context_to_sid_raw") at assert.c:101
#4  0x0000ffffb8e2178c in avc_context_to_sid_raw (ctx=0xaaaafd593b80 "unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023", sid=<optimized out>) at avc.c:74
#5  0x0000ffffb8e217cc in avc_context_to_sid (ctx=ctx@entry=0xaaaafd568010 "unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023", sid=0xffffc9526938,
    sid@entry=0xffffc9526978) at avc.c:90
#6  0x0000ffffb8e24cbc in selinux_check_access (scon=0xaaaafd568010 "unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023", scon@entry=0xaaaacfa5b000 "",
    tcon=tcon@entry=0xaaaafd591830 "unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023", class=class@entry=0xffffb853a410 "context",
    perm=perm@entry=0xffffb853a400 "contains", aux=aux@entry=0x0) at checkAccess.c:34
#7  0x0000ffffb8539c44 in context_from_env (debug=0, use_current_range=0, env_params=1, defaultcon=0xaaaacfa5b000 "", pamh=0x0) at pam_selinux.c:356
#8  compute_exec_context (debug=0, env_params=1, use_current_range=0, select_context=<optimized out>, data=0xaaaafd592590, pamh=0x0) at pam_selinux.c:501
#9  create_context (verbose=<optimized out>, debug=<optimized out>, argv=<optimized out>, argc=<optimized out>, pamh=<optimized out>) at pam_selinux.c:711
#10 pam_sm_open_session (pamh=0x0, flags=<optimized out>, argc=<optimized out>, argv=<optimized out>) at pam_selinux.c:789
#11 0x0000ffffb92e862c in _pam_dispatch_aux (use_cached_chain=<optimized out>, resumed=<optimized out>, h=0xaaaafd58ba70, flags=0, pamh=0xaaaafd5811e0)
    at pam_dispatch.c:110
#12 _pam_dispatch (pamh=0xaaaafd5811e0, flags=flags@entry=0, choice=choice@entry=4) at pam_dispatch.c:426
#13 0x0000ffffb92ecbc8 in pam_open_session (pamh=<optimized out>, flags=flags@entry=0) at pam_session.c:23
#14 0x0000aaaacf9b193c in do_pam_session (ssh=0xaaaafd571810) at auth-pam.c:1196
#15 0x0000aaaacf98d058 in main (ac=<optimized out>, av=<optimized out>) at sshd.c:2405
```

**Comment by sethmoo** [comment]
I attempted (and failed to submit) a fix here: https://lore.kernel.org/selinux/CAJsHiNx1E7x1jaBkS0i4L1nBWXp8YXLHRWcCaDaH4LOn=zm+Zw@mail.gmail.com/

In Android keystore2, we continue to treat libselinux as _not_ thread safe, and we serialize all calls to it.

**Comment by stephensmalley** [comment]
I know it's been a minute since this issue was opened but PTAL at this RFC series, https://lore.kernel.org/selinux/20260612170856.17904-1-stephen.smalley.work@gmail.com/T/#t

**Comment by stephensmalley** [comment]
Updated series at https://lore.kernel.org/selinux/20260612191146.20122-1-stephen.smalley.work@gmail.com/T/#t
