### ISSUE TITLE
selinux-polgengui: Error when manually specifying the path to the sock

### ISSUE THREAD

**Issue by freedom1b2830** [SELinuxProject/selinux#379]
- At the phase of choosing paths to files, I choose the path to the ``unix socket``.
in the console writes an error below, graphically does not warn.
- After the generation of the ``te if fc`` file is completed, it turns out that the ``fc`` file is empty (size 0)
- arch linux package version ``selinux-gui 3.4-1``
```
Traceback (most recent call last):
  File "/usr/bin/selinux-polgengui", line 390, in forward
    self.generate_policy()
  File "/usr/bin/selinux-polgengui", line 536, in generate_policy
    self.info(my_policy.generate(outputdir))
  File "/usr/lib/python3.10/site-packages/sepolicy/generate.py", line 1378, in generate
    out += "%s # %s\n" % (self.write_fc(out_dir), _("File Contexts file"))
  File "/usr/lib/python3.10/site-packages/sepolicy/generate.py", line 1259, in write_fc
    fd.write(self.generate_fc())
  File "/usr/lib/python3.10/site-packages/sepolicy/generate.py", line 1094, in generate_fc
    t1 = re.sub("TEMPLATETYPE", self.name, self.files[i][2].fc_sock_file)
AttributeError: module 'sepolicy.templates.tmp' has no attribute 'fc_sock_file'
```

**Comment by stephensmalley** [comment]
Possible fix at https://github.com/stephensmalley/selinux/commit/ec383ed10e6505abe6d1fe1e57dec4da5d13b154
