### ISSUE TITLE
Error Parsing Headers: Missing `obj_perm_sets.spt` During Functional Testing

### ISSUE THREAD

**Issue by 3ks** [SELinuxProject/selinux#451]
## Overview
I built SELinux from source and attempted to perform functional testing. However, I encountered the following error:

```
error parsing headers: could not find support macros (obj_perm_sets.spt)
```

I am unsure how to check for or install the `obj_perm_sets.spt` file. Any assistance in resolving this issue would be greatly appreciated.

## Operating System Versions

- CentOS 8
- Ubuntu 22 LTS

## SELinux Code Versions Tried

- 3.5
- 3.6
- 3.7

## Scripts

```
dnf install -y audit-libs-devel bison bzip2-devel CUnit-devel diffutils flex gcc gettext glib2-devel make libcap-devel libcap-ng-devel pam-devel pcre2-devel xmlto python3-devel python3-pip python3-setuptools python3-wheel ruby-devel swig

groupadd mock && useradd -g mock mock && su mock

cd ~/ && git clone https://github.com/SELinuxProject/selinux.git && cd selinux && git checkout selinux-python-3.7

make clean distclean && make DESTDIR=~/obj install install-rubywrap install-pywrap

DESTDIR=~/obj ./scripts/env_use_destdir make test
```

It appears that the build successfully passed hundreds of tests. I have tried multiple operating systems and code versions, but the issue persists. 

I carefully read the README.md content and noticed the following section:

> Some tests require the reference policy to be installed (for example in python/sepolgen).

I am unsure if this is related to the error and how to correctly install the reference policy. Since I am not very familiar with SELinux, I would greatly appreciate your help.

## `make test` Detailed Logs

```
~/selinux [(tags/checkpolicy-3.5) *] $ DESTDIR=~/obj ./scripts/env_use_destdir make test
make[1]: Entering directory '/home/mock/selinux/libsepol'
make -C tests test
make[2]: Entering directory '/home/mock/selinux/libsepol/tests'
env -i mkdir -p policies/test-downgrade
../../checkpolicy/checkpolicy -M policies/test-cond/refpolicy-base.conf -o policies/test-downgrade/policy.hi
./libsepol-tests


     CUnit - A unit testing framework for C - Version 2.1-3
     http://cunit.sourceforge.net/


Suite: ebitmap
  Test: ebitmap_init_destroy ...passed
  Test: ebitmap_cmp ...passed
  Test: ebitmap_set_and_get ...passed
  Test: ebitmap_init_range ...passed
  Test: ebitmap_or ...passed
  Test: ebitmap_and ...passed
  Test: ebitmap_xor ...passed
  Test: ebitmap_not ...passed
  Test: ebitmap_andnot ...passed
  Test: ebitmap__random ...passed
Suite: cond
  Test: cond_expr_equal ...passed
Suite: linker
  Test: linker_indexes ...passed
  Test: linker_types ...passed
  Test: linker_roles ...passed
  Test: linker_cond ...passed
Suite: expander
  Test: expander_indexes ...passed
  Test: expander_attr_mapping ...passed
  Test: expander_role_mapping ...passed
  Test: expander_user_mapping ...passed
  Test: expander_alias ...passed
Suite: deps
  Test: deps_modreq_global ...passed
  Test: deps_modreq_opt ...passed
Suite: downgrade
  Test: downgrade ...passed
Suite: neverallow
  Test: neverallow_basic ...passed

Run Summary:    Type  Total    Ran Passed Failed Inactive
              suites      7      7    n/a      0        0
               tests     24     24     24      0        0
             asserts 854586 854586 854586      0      n/a

Elapsed time =    2.679 seconds


     CUnit - A unit testing framework for C - Version 2.1-3
     http://cunit.sourceforge.net/


Suite: ebitmap
  Test: ebitmap_init_destroy ...passed
  Test: ebitmap_cmp ...passed
  Test: ebitmap_set_and_get ...passed
  Test: ebitmap_init_range ...passed
  Test: ebitmap_or ...passed
  Test: ebitmap_and ...passed
  Test: ebitmap_xor ...passed
  Test: ebitmap_not ...passed
  Test: ebitmap_andnot ...passed
  Test: ebitmap__random ...passed
Suite: cond
  Test: cond_expr_equal ...passed
Suite: linker
  Test: linker_indexes ...passed
  Test: linker_types ...passed
  Test: linker_roles ...passed
  Test: linker_cond ...passed
Suite: expander
  Test: expander_indexes ...passed
  Test: expander_attr_mapping ...passed
  Test: expander_role_mapping ...passed
  Test: expander_user_mapping ...passed
  Test: expander_alias ...passed
Suite: deps
  Test: deps_modreq_global ...passed
  Test: deps_modreq_opt ...passed
Suite: downgrade
  Test: downgrade ...passed

Run Summary:    Type  Total    Ran Passed Failed Inactive
              suites      7      7    n/a      0        0
               tests     23     23     23      0        0
             asserts 854636 854636 854636      0      n/a

Elapsed time =    2.535 seconds
make[2]: Leaving directory '/home/mock/selinux/libsepol/tests'
make[1]: Leaving directory '/home/mock/selinux/libsepol'
make[1]: Entering directory '/home/mock/selinux/libselinux'
make[1]: Nothing to be done for 'test'.
make[1]: Leaving directory '/home/mock/selinux/libselinux'
make[1]: Entering directory '/home/mock/selinux/libsemanage'
make -C src all
make[2]: Entering directory '/home/mock/selinux/libsemanage/src'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/mock/selinux/libsemanage/src'
make -C tests test
make[2]: Entering directory '/home/mock/selinux/libsemanage/tests'
./libsemanage-tests


     CUnit - A unit testing framework for C - Version 2.1-3
     http://cunit.sourceforge.net/


Suite: semanage_store
  Test: semanage_store_access_check ...passed
  Test: semanage_get_lock ...passed
  Test: semanage_nc_sort ...passed
Suite: semanage_utilities
  Test: semanage_is_prefix ...passed
  Test: semanage_split_on_space ...passed
  Test: semanage_split ...passed
  Test: semanage_list ...passed
  Test: semanage_str_count ...passed
  Test: semanage_rtrim ...passed
  Test: semanage_str_replace ...passed
  Test: semanage_findval ...passed
  Test: slurp_file_filter ...passed
Suite: handle
  Test: test_handle_create ...passed
  Test: test_connect ...passed
  Test: test_disconnect ...passed
  Test: test_transaction ...passed
  Test: test_commit ...passed
  Test: test_is_connected ...passed
  Test: test_access_check ...passed
  Test: test_is_managed ...passed
  Test: test_mls_enabled ...passed
  Test: msg_set_callback ...passed
  Test: test_root ...passed
  Test: test_select_store ...passed
Suite: bool
  Test: bool_key_create ...passed
  Test: bool_key_extract ...passed
  Test: bool_compare ...passed
  Test: bool_compare2 ...passed
  Test: bool_get_set_name ...passed
  Test: bool_get_set_value ...passed
  Test: bool_create ...passed
  Test: bool_clone ...passed
  Test: bool_query ...passed
  Test: bool_exists ...passed
  Test: bool_count ...passed
  Test: bool_iterate ...passed
  Test: bool_list ...passed
  Test: bool_modify_del_local ...passed
  Test: bool_query_local ...passed
  Test: bool_exists_local ...passed
  Test: bool_count_local ...passed
  Test: bool_iterate_local ...passed
  Test: bool_list_local ...passed
Suite: fcontext
  Test: test_fcontext_compare ...passed
  Test: test_fcontext_compare2 ...passed
  Test: test_fcontext_key_create ...passed
  Test: test_fcontext_key_extract ...passed
  Test: test_fcontext_get_set_expr ...passed
  Test: test_fcontext_get_set_type ...passed
  Test: test_fcontext_get_type_str ...passed
  Test: test_fcontext_get_set_con ...passed
  Test: test_fcontext_create ...passed
  Test: test_fcontext_clone ...passed
  Test: test_fcontext_query ...passed
  Test: test_fcontext_exists ...passed
  Test: test_fcontext_count ...passed
  Test: test_fcontext_iterate ...passed
  Test: test_fcontext_list ...passed
  Test: test_fcontext_modify_del_local ...passed
  Test: test_fcontext_query_local ...passed
  Test: test_fcontext_exists_local ...passed
  Test: test_fcontext_count_local ...passed
  Test: test_fcontext_iterate_local ...passed
  Test: test_fcontext_list_local ...passed
Suite: iface
  Test: iface_compare ...passed
  Test: iface_compare2 ...passed
  Test: iface_key_create ...passed
  Test: iface_key_extract ...passed
  Test: iface_get_set_name ...passed
  Test: iface_get_set_ifcon ...passed
  Test: iface_get_set_msgcon ...passed
  Test: iface_create) ...passed
  Test: iface_clone); ...passed
  Test: iface_query ...passed
  Test: iface_exists ...passed
  Test: iface_count ...passed
  Test: iface_iterate ...passed
  Test: iface_list ...passed
  Test: iface_modify_del_query_local ...passed
  Test: iface_exists_local ...passed
  Test: iface_count_local ...passed
  Test: iface_iterate_local ...passed
  Test: iface_list_local ...passed
Suite: ibendport
  Test: ibendport_query ...passed
  Test: ibendport_exists ...passed
  Test: ibendport_count ...passed
  Test: ibendport_iterate ...passed
  Test: ibendport_list ...passed
  Test: ibendport_modify_del_query_local ...passed
  Test: ibendport_exists_local ...passed
  Test: ibendport_count_local ...passed
  Test: ibendport_iterate_local ...passed
  Test: ibendport_list_local ...passed
Suite: node
  Test: node_compare ...passed
  Test: node_compare2 ...passed
  Test: node_key_create ...passed
  Test: node_key_extract ...passed
  Test: node_get_set_addr ...passed
  Test: node_get_set_addr_bytes ...passed
  Test: node_get_set_mask ...passed
  Test: node_get_set_mask_bytes ...passed
  Test: node_get_set_proto ...passed
  Test: node_get_proto_str ...passed
  Test: node_get_set_con ...passed
  Test: node_create ...passed
  Test: node_clone ...passed
  Test: node_query ...passed
  Test: node_exists ...passed
  Test: node_count ...passed
  Test: node_iterate ...passed
  Test: node_list ...passed
  Test: node_modify_del_query_local ...passed
  Test: node_exists_local ...passed
  Test: node_count_local ...passed
  Test: node_iterate_local ...passed
  Test: node_list_local ...passed
Suite: port
  Test: port_compare ...passed
  Test: port_compare2 ...passed
  Test: port_key_create ...passed
  Test: port_key_extract ...passed
  Test: port_get_set_proto ...passed
  Test: port_get_proto_str ...passed
  Test: port_get_set_port ...passed
  Test: port_get_set_con ...passed
  Test: port_create ...passed
  Test: port_clone ...passed
  Test: port_query ...passed
  Test: port_exists ...passed
  Test: port_count ...passed
  Test: port_iterate ...passed
  Test: port_list ...passed
  Test: port_modify_del_local ...passed
  Test: port_query_local ...passed
  Test: port_exists_local ...passed
  Test: port_count_local ...passed
  Test: port_iterate_local ...passed
  Test: port_list_local ...passed
  Test: port_validate_local ...passed
Suite: user
  Test: user_compare ...passed
  Test: user_compare2 ...passed
  Test: user_key_create ...passed
  Test: user_key_extract ...passed
  Test: user_get_set_name ...passed
  Test: user_get_set_prefix ...passed
  Test: user_get_set_mlslevel ...passed
  Test: user_get_set_mlsrange ...passed
  Test: user_roles ...passed
  Test: user_create ...passed
  Test: user_clone ...passed
  Test: user_query ...passed
  Test: user_exists ...passed
  Test: user_count ...passed
  Test: user_iterate ...passed
  Test: user_list ...passed
  Test: user_modify_del_query_local ...passed
  Test: user_exists_local ...passed
  Test: user_count_local ...passed
  Test: user_iterate_local ...passed
  Test: user_list_local ...passed
Suite: other
  Test: semanage_context ...passed
  Test: debug ...libsemanage.semanage_module_info_set_priority: Priority 65494 is invalid.
passed

Run Summary:    Type  Total    Ran Passed Failed Inactive
              suites     11     11    n/a      0        0
               tests    161    161    161      0        0
             asserts   3233   3233   3233      0      n/a

Elapsed time =    0.074 seconds
make[2]: Leaving directory '/home/mock/selinux/libsemanage/tests'
make[1]: Leaving directory '/home/mock/selinux/libsemanage'
make[1]: Entering directory '/home/mock/selinux/checkpolicy'
make[1]: Nothing to be done for 'test'.
make[1]: Leaving directory '/home/mock/selinux/checkpolicy'
make[1]: Entering directory '/home/mock/selinux/secilc'
./secilc test/policy.cil
./secilc -c 33 -O -M 1 -f /dev/null -o opt-actual.bin test/opt-input.cil
checkpolicy -b -C -M -o opt-actual.cil opt-actual.bin >/dev/null
diff test/opt-expected.cil opt-actual.cil
make[1]: Leaving directory '/home/mock/selinux/secilc'
make[1]: Entering directory '/home/mock/selinux/policycoreutils'
make[1]: Nothing to be done for 'test'.
make[1]: Leaving directory '/home/mock/selinux/policycoreutils'
make[1]: Entering directory '/home/mock/selinux/dbus'
make[1]: Nothing to be done for 'test'.
make[1]: Leaving directory '/home/mock/selinux/dbus'
make[1]: Entering directory '/home/mock/selinux/gui'
make[1]: Nothing to be done for 'test'.
make[1]: Leaving directory '/home/mock/selinux/gui'
make[1]: Entering directory '/home/mock/selinux/mcstrans'
make[1]: Nothing to be done for 'test'.
make[1]: Leaving directory '/home/mock/selinux/mcstrans'
make[1]: Entering directory '/home/mock/selinux/python'
make[2]: Entering directory '/home/mock/selinux/python/sepolicy'
SELinux must be in enforcing mode for this test
make[2]: Leaving directory '/home/mock/selinux/python/sepolicy'
make[2]: Entering directory '/home/mock/selinux/python/audit2allow'
test_audit2allow (__main__.Audit2allowTests.test_audit2allow)
Verify audit2allow works ... ok
test_audit2why (__main__.Audit2allowTests.test_audit2why)
Verify audit2why works ... ok
test_sepolgen_ifgen (__main__.Audit2allowTests.test_sepolgen_ifgen)
Verify sepolgen-ifgen works ... error parsing headers: could not find support macros (obj_perm_sets.spt)
FAIL
test_xperms (__main__.Audit2allowTests.test_xperms)
Verify that xperms generation works ... ok

======================================================================
FAIL: test_sepolgen_ifgen (__main__.Audit2allowTests.test_sepolgen_ifgen)
Verify sepolgen-ifgen works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mock/selinux/python/audit2allow/test_audit2allow.py", line 38, in test_sepolgen_ifgen
    self.assertSuccess("sepolgen-ifgen", p.returncode, err)
  File "/home/mock/selinux/python/audit2allow/test_audit2allow.py", line 24, in assertSuccess
    self.assertTrue(status == 0,
AssertionError: False is not true : "sepolgen-ifgen should have succeeded for this test None

----------------------------------------------------------------------
Ran 4 tests in 0.232s

FAILED (failures=1)
make[2]: *** [Makefile:28: test] Error 1
make[2]: Leaving directory '/home/mock/selinux/python/audit2allow'
make[1]: *** [Makefile:4: test] Error 1
make[1]: Leaving directory '/home/mock/selinux/python'
make: *** [Makefile:40: test] Error 1
~/selinux [(tags/checkpolicy-3.5) *] $ 
```

**Comment by 3ks** [comment]
I resolved this issue after installed https://github.com/SELinuxProject/refpolicy
